## 1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [1]:
import numpy as np

In [29]:
arr1 = np.random.randint(0,10,10)
arr1


array([3, 7, 0, 0, 6, 2, 0, 6, 4, 5])

In [30]:
def contains_zero(arr):
    total_len = len(arr)
    arr2 = arr[arr!=0]
    partial_len = len(arr2)
    return not(total_len == partial_len)

In [31]:
print(contains_zero(arr1))
arr2 = np.ones(3)
print(contains_zero(arr2))

True
False


## 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [32]:
def contains_non_zero(arr):
    total_len = len(arr)
    arr2 = arr[arr==0]
    partial_len = len(arr2)
    return not(total_len == partial_len)

In [33]:
arr1 = np.zeros(3)
arr2 = np.ones(3)
arr3 = np.random.randint(0,10,10)
print(contains_non_zero(arr1))
print(contains_non_zero(arr2))
print(contains_non_zero(arr3))

False
True
True


## 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given 

In [34]:
def is_equal(arr1, arr2):
    return arr1==arr2

In [37]:
arr1 = np.ones(4)
arr2 = np.zeros(4)
is_equal(arr1, arr2)

array([False, False, False, False])

## 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [40]:
arr_zeros = np.zeros(10)
arr_ones = np.ones(10)
arr_fives = np.random.randint(5,6,10)
print(arr_zeros, arr_ones, arr_fives)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [5 5 5 5 5 5 5 5 5 5]


## 5. Write a NumPy program to create an array of the integers from 30 to70

In [41]:
arr_int = np.random.randint(30,70,15)
arr_int

array([50, 64, 56, 58, 39, 54, 39, 35, 36, 40, 59, 67, 43, 47, 34])

## 6. Write a NumPy program to create a 3x3 identity matrix 

In [43]:
identity_matrix = np.identity(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 7. Write a NumPy program to generate a random number between 0 and 1 

In [55]:
arr_random = np.linspace(0,1,7)
arr_random

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

## 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution 

In [57]:
arr_random = np.random.randn(15)
arr_random

array([-1.36934205,  0.52501725,  0.03571489, -0.40737407,  0.63650594,
       -0.6531274 ,  1.62958801, -0.08587888,  0.24674833, -1.47644726,
        1.35142071, -0.68582322,  0.46517689, -0.3120313 , -1.28053018])

## 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

In [60]:
range_vector = np.array(((np.random.randint(15,55,10))))
range_vector[1:-1]

array([32, 46, 21, 25, 43, 51, 54, 37])

## 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10 

In [63]:
vector_1 = np.random.randint(0,10,5)
vector_1


array([3, 9, 2, 4, 0])

## 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [70]:
zero_one = np.ones((10,10))
zero_one[1:-1 , 1:-1] = 0
zero_one

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [74]:
zero_matrix = np.zeros((5,5))
for i in range(len(zero_matrix)):
    zero_matrix[i, i] = i + 1
zero_matrix

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

## 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.


In [77]:
staggered_matrix = np.ones((4,4))
for i in range(len(staggered_matrix)):
    staggered_matrix[i,i]=0
    if i+2 < 4:
        staggered_matrix[i,i+2]=0
    else:
        staggered_matrix[i,i-2]=0
staggered_matrix

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

## 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it

In [87]:
arr1 = np.random.randint(1,10,10)
arr2 = np.random.randint(10,20,10)
np.savez_compressed('arrays.npz',arr1=arr1,arr2=arr2)
loaded_data = np.load('arrays.npz')
loaded_arr1 = loaded_data['arr1']
print(arr1)
print(loaded_arr1)

[7 7 5 1 2 9 8 8 3 7]
[7 7 5 1 2 9 8 8 3 7]


## 15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select 

In [88]:
oneD = np.random.rand(40)
oneD

array([0.42126576, 0.7008643 , 0.82191095, 0.50136463, 0.60743352,
       0.48794159, 0.27224478, 0.26352943, 0.66653806, 0.85143763,
       0.7139832 , 0.03293814, 0.06073602, 0.38714697, 0.63339634,
       0.08105626, 0.35512844, 0.26232693, 0.39978177, 0.55622233,
       0.55414166, 0.9552885 , 0.79017992, 0.08800753, 0.10469658,
       0.40014159, 0.40098875, 0.16866301, 0.90150094, 0.02863154,
       0.80547103, 0.43572773, 0.19971096, 0.61477178, 0.18748272,
       0.59665885, 0.13491558, 0.69464634, 0.93481797, 0.00571221])

## 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [90]:
arr1 = np.random.randint(0,100,40)
print(arr1)
print(f'The array elements that are less than 50: {arr1[arr1<=50]}')
print(f'The array elements that are greater than 50: {arr1[arr1>50]}')

[31 28 53 54 32 77 78 49 58 26  4 57 31 45 33 45 14 77 46 25 25 13 51 28
 33 16 85 99 85 64 73 39  3 24 44  4 98 42 55 86]
The array elements that are less than 50: [31 28 32 49 26  4 31 45 33 45 14 46 25 25 13 28 33 16 39  3 24 44  4 42]
The array elements that are greater than 50: [53 54 77 78 58 57 77 51 85 99 85 64 73 98 55 86]
