# Numpy

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
numpy_arr = np.array(my_list)
print(numpy_arr)
print(type(numpy_arr))

[1 2 3]
<class 'numpy.ndarray'>


In [15]:
random_arr = np.empty([3,4])
random_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
zeros_arr = np.zeros([5,4])
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
ones_arr = np.ones((3,4))
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
vertical_arr = np.vstack((zeros_arr,ones_arr))
# horizontal_arr = np.hstack((zeros_arr,ones_arr))

vertical_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
horizontal_arr

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [23]:
arr = np.array([[1,3,4,5],[2,6,4,3]])
print('3',arr[-1,-1])

3 3


In [92]:
data = np.array(([1,3,4,7,5],
                [4,6,4,7,2],
                [3,6,2,8,1],
                [1,4,5,6,3],
                [6,3,6,4,3],
                [10,9,10,9,10])
               )
x = data[:,:-1]
y = data[:,-1]
print(x)
print(type(y))
print(y)

[[ 1  3  4  7]
 [ 4  6  4  7]
 [ 3  6  2  8]
 [ 1  4  5  6]
 [ 6  3  6  4]
 [10  9 10  9]]
<class 'numpy.ndarray'>
[ 5  2  1  3  3 10]


In [59]:
train = data[:3,:]
test = data[3:, :]
print(train)
print()
print(test)

[[1 3 4 7 5]
 [4 6 4 7 2]
 [3 6 2 8 1]]

[[1 4 5 6 3]
 [6 3 6 4 3]]


In [60]:
print(x)
print(y)

[[1 3 4 7]
 [4 6 4 7]
 [3 6 2 8]
 [1 4 5 6]
 [6 3 6 4]]
[5 2 1 3 3]


In [64]:
X_train, X_test = x[:3,:], x[3:,:]
print(X_train)
print()
print(X_test)
print()

y_train, y_test = y[:3],y[3:]
print(y_train)
print()
print(y_test)


[[1 3 4 7]
 [4 6 4 7]
 [3 6 2 8]]

[[1 4 5 6]
 [6 3 6 4]]

[5 2 1]

[3 3]


In [88]:
def split_data(data,perc):
    x = data[:,:-1]
    y = data[:,-1]
    perc = int((perc/100)* len(data))
    X_train, X_test = x[:perc,:], x[perc:,:]
    y_train, y_test = y[:perc],y[perc:]
    return X_train, X_test,y_train, y_test



In [94]:
print(data)
print()
X_train, X_test,y_train, y_test = split_data(data,50)
print(f'{X_train}\n\n{X_test}\n\n{y_train}\n\n{y_test}\n\n')


[[ 1  3  4  7  5]
 [ 4  6  4  7  2]
 [ 3  6  2  8  1]
 [ 1  4  5  6  3]
 [ 6  3  6  4  3]
 [10  9 10  9 10]]

[[1 3 4 7]
 [4 6 4 7]
 [3 6 2 8]]

[[ 1  4  5  6]
 [ 6  3  6  4]
 [10  9 10  9]]

[5 2 1]

[ 3  3 10]




In [117]:
data = np.array(([1,4],[6,7]))

In [106]:
data.shape
data.reshape(1,data.shape[0])

array([[1, 4, 5, 6, 7]])

In [110]:
print(x.shape)

(6, 4)


In [109]:
(x.T).shape

(4, 6)

In [111]:
x.T

array([[ 1,  4,  3,  1,  6, 10],
       [ 3,  6,  6,  4,  3,  9],
       [ 4,  4,  2,  5,  6, 10],
       [ 7,  7,  8,  6,  4,  9]])

In [118]:
np.linalg.det(data)

-17.0

In [126]:
data

array([[1, 4],
       [6, 7]])

In [131]:
np.dot(np.linalg.inv(data),data)

array([[1., 0.],
       [0., 1.]])

In [129]:
(np.linalg.inv(data.T)).T

array([[-0.41176471,  0.23529412],
       [ 0.35294118, -0.05882353]])